version: '3.8'

services:
  urbalurba-dropbox:
    image: janeczku/dropbox
    environment:
      - DBOX_TOKEN=sl.BjySS0rZxqElO0qJCrr4v6LcMuvmP0exthAkg2jGa5E2hZ-cwcb-juFWvxyX4pSjYcGOS7h-9bPcoivP2Xkr-CKWnWgoeBvP0Ey2rcobJI8jOLFFv1P5jcSqs6cxQluctVf7YtzgGYPP
      - DBOX_UID=0
      - DBOX_GID=0
      - $DBOX_SKIP_UPDATE=True
    command: ["dropbox"]
    volumes:
      - urbalurbafiles:/dbox/Dropbox
    networks:
      - urbalurba-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  urbalurbafiles:
    external:
      name: urbalurba_urbalurbafiles


networks:
  urbalurba-network:
    external: true
