version: '3.7'
services:
  urbalurba-dropbox:
    image: urbalurba-dropbox:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DROPBOX_DIR: /sync
    volumes:
#      - ${URBALURBAFILES_VOLUME_NAME:-urbalurbafiles}:/sync
      - urbalurbafiles:/sync
      - dropbox_data:/dropbox
    networks:
      - urbalurba-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  urbalurbafiles:
    external:
      name: urbalurba_urbalurbafiles
  dropbox_data:

networks:
  urbalurba-network:
    external: true
